// More Note Check questions, covering the whole note process: structure,
// timing, every kind of interaction (calls, voicemails, transfers to
// Customer Care, escalations, damages, reschedules, driver reports),
// sensitive data, wording, and how QA reads a note. Merged into QUIZ_BANK
// (notesQuiz.ts). Compact form: [id, prompt, options, correct option, tip].
// The correct option's position doesn't matter — options are shuffled per day.
import type { QuizQuestion } from "./notesQuiz";

type Q = [string, string, string[], number, string];

const RAW: Q[] = [
  // ---- Structure
  ["s-order", "What’s the best order for a note?", ["Outcome first, then who", "Who → what happened → what you did → next step", "Any order, as long as it’s long", "Only the next step"], 1, "Who · what · outcome · next step. A familiar order lets anyone scan it in seconds."],
  ["s-who-third", "The customer’s neighbor called about the delivery. How do you note who you spoke with?", ["Spoke with customer", "Spoke with Ana Ruiz (neighbor, not account holder), calling for the account holder", "Spoke with someone", "No need to say"], 1, "Always say who it was and their relationship to the account — it changes what you can share."],
  ["s-channel", "Why note the channel (inbound call, outbound, chat, email)?", ["It doesn’t matter", "So the next agent knows how contact happened and how to follow up", "Only for chats", "QA asks for it only on Mondays"], 1, "The channel tells the next person how to reach the customer the same way."],
  ["s-next-owner", "A good next step says…", ["“TBD”", "What happens, who owns it and when", "“Customer will call”", "Nothing — the case is open"], 1, "What, who and when. Without an owner, nobody does it."],
  ["s-outcome", "The customer hung up before you could finish. What’s the outcome?", ["Leave it blank", "Call disconnected before resolution; attempted callback at 2:14 pm ET, no answer", "Customer rude", "Resolved"], 1, "An unfinished call still has an outcome: say where it stopped and what you did next."],
  ["s-numbers", "Which details should be exact in a note?", ["Dates, times, reference numbers and amounts", "Only the customer’s mood", "Approximate dates are fine", "Nothing needs to be exact"], 0, "Numbers and dates are what people act on. Get them exactly right."],
  ["s-short", "Which note is better?", ["Long story of the whole call, minute by minute", "Short and complete: who, what, outcome, next step"], 1, "Complete beats long. Cut the story, keep the facts."],
  ["s-timezone", "You promise a callback “at 3 pm”. What’s missing?", ["Nothing", "The time zone (e.g. 3 pm ET) and the date", "The customer’s age", "Your break time"], 1, "Customers and agents are in different zones. Write the date and the zone."],
  ["s-one-case", "The customer asked about two different orders. How do you note it?", ["One vague note for both", "Clear notes for each order, with each order’s number and outcome", "Only note the first one", "Skip it"], 1, "Each case needs its own facts and next step, or one of them gets lost."],
  // ---- Timing & process
  ["p-during", "When should you start writing the note?", ["During the interaction, finishing right after", "At the end of the day", "Only if QA asks", "Tomorrow morning"], 0, "Start while it’s happening, finish right after. Details fade fast."],
  ["p-backlog", "You have 3 calls without notes. What do you do?", ["Skip them, they’re done", "Write them now, before taking more interactions", "Write one note for all three", "Wait until Friday"], 1, "Catch up right away — the longer you wait, the less accurate they get."],
  ["p-correction", "You wrote the wrong delivery date in a note. What now?", ["Delete the note", "Add a new note correcting it, with the right date", "Leave it, nobody will notice", "Edit the customer’s address too"], 1, "Correct it with a new dated note. The timeline must stay honest."],
  ["p-followup-done", "You made the callback you promised yesterday. What’s the note?", ["Nothing, it was already noted", "A new note: callback made, who you spoke with, outcome and any next step", "Just “done”", "Delete yesterday’s note"], 1, "Close the loop: every promise in a note gets a follow-up note."],
  ["p-hold", "You put the customer on hold to check with a lead. Do you note it?", ["No", "Yes: what you checked, with whom, and what you learned", "Only if the hold was long", "Only if they complained"], 1, "What the lead said is part of the case. Write it down."],
  ["p-chat-email", "The customer also sent an email about the same issue. What do you note?", ["Nothing, emails are separate", "That an email was received, what it said and what you did with it", "Only the subject line", "Forward it and forget it"], 1, "Every channel feeds the same story. Note it in the account."],
  ["p-repeat-caller", "The customer is calling for the third time about the same delivery. First thing to do?", ["Start from zero", "Read the previous notes, then add yours to the same timeline", "Transfer immediately", "Ask them to call tomorrow"], 1, "Previous notes save the customer from repeating everything. Read before you act."],
  ["p-multiple-attempts", "You tried calling 3 times with no answer. What’s in the note?", ["“Couldn’t reach”", "Each attempt: time, number and whether a VM was left", "Nothing until you reach them", "Just the last attempt"], 1, "Every attempt proves the effort — and stops someone from calling a 4th time by mistake."],
  ["p-wrong-number", "The number on the account is wrong. What do you note?", ["Nothing", "Number called, that it’s not the customer’s, and the next step to get a valid contact", "Delete the number", "“Bad number”"], 1, "Say what was tried and what happens next so the next agent doesn’t dial it again."],
  ["p-silence", "The call had no audio and dropped. Note it?", ["No, nothing happened", "Yes: inbound/outbound, time, no audio, call dropped, and any callback attempt", "Only if it happens twice", "Only on chats"], 1, "Even a dropped call is an interaction. Note it so the history is complete."],
  // ---- Transfers & Customer Care
  ["t-customer-care", "The customer needs help with something our team doesn’t handle. Where do they go, and what do you note?", ["Tell them to search online", "Transfer to Customer Care and note why and what the customer needs", "Hang up politely", "Note nothing"], 1, "Customer Care handles everything outside our scope. Note why you transferred and what they need."],
  ["t-warm", "What makes a warm transfer note?", ["“Transferred”", "Who you transferred to, why, and what the customer already explained", "The time only", "The customer’s mood"], 1, "A warm hand-off means the customer doesn’t start over."],
  ["t-return", "The customer wants to return an item. Our team doesn’t process returns. Best note?", ["Customer wants return.", "Customer wants to return the dryer (order #); transferred to Customer Care to handle the return.", "Told them no.", "Nothing"], 1, "Name the item, the reason and where they went — Customer Care takes it from there."],
  ["t-before", "Before transferring a call, you should…", ["Transfer as fast as possible, no note", "Write a quick note so the next team sees what happened", "Wait until after the call ends", "Ask the customer to write it down"], 1, "A note before the transfer travels with the customer."],
  // ---- Deliveries, reschedules, damages
  ["d-reschedule-why", "Why note WHO asked for a reschedule?", ["It doesn’t matter", "It changes the case: a customer request vs. our delay are handled differently", "Only for long reschedules", "To blame someone"], 1, "Who asked and why explains the change to anyone reviewing it later."],
  ["d-window", "What delivery detail must a reschedule note include?", ["The new date and the delivery window", "The weather", "The driver’s name only", "The truck’s color"], 0, "New date and window — that’s what the customer and the team plan around."],
  ["d-damage-photos", "The customer reports damage and sends photos. Your note includes…", ["“Damage reported”", "What’s damaged, when it was noticed, that photos were received, and the claim/reference number", "The photos’ file names only", "Your opinion of the damage"], 1, "Item, damage, evidence, reference. That’s what the claim needs."],
  ["d-missed", "A delivery was missed. What makes the note useful?", ["“Missed delivery”", "What happened (per driver/system), contact attempts, and the new plan with date", "An apology", "The customer’s tone"], 1, "Facts, attempts and the plan — so the next call starts from the solution."],
  ["d-partial", "Only part of the order arrived. Best note?", ["Partial delivery.", "Delivered: fridge. Missing: water line kit (order #). Customer informed; follow-up opened #, ETA 6/18.", "Customer upset.", "Will check."], 1, "List what came, what didn’t, the reference and the ETA."],
  ["d-access", "The customer gave a gate code for the delivery. Where does it go?", ["In the note, in capital letters", "Only in the delivery instructions field your process allows — not in a general note", "Nowhere", "In the chat with your team"], 1, "Access codes are sensitive. Use the field meant for them, not free-text notes."],
  ["d-driver-source", "A driver reports the address doesn’t exist. You write…", ["Address doesn’t exist.", "Driver (route 7) reports address not found at 10:20; called customer to confirm, no answer, VM left.", "Customer gave a fake address.", "Nothing"], 1, "Say where the information came from — a driver report isn’t the same as a confirmed fact."],
  ["d-install", "The customer asks about installation. Our team doesn’t schedule it. Note?", ["Nothing", "Customer asked about installation; explained it’s outside our scope and transferred to Customer Care", "“Can’t help”", "Promise an installer"], 1, "Never promise what we don’t own. Note the request and the hand-off."],
  // ---- Escalations & promises
  ["e-supervisor", "The customer asks for a supervisor and one isn’t available. What do you note?", ["Nothing", "The request, that no supervisor was available, and the callback you scheduled (date/time)", "“Escalated”", "That the customer was difficult"], 1, "The request and the promise you made both belong in the note."],
  ["e-promise", "Which promise is OK to put in a note?", ["“We’ll fix everything today”", "Only what you can actually commit to, with a date", "“Free delivery forever”", "None — never promise anything"], 1, "Only promise what’s real, and write it down so the team can keep it."],
  ["e-refund", "The customer asks for a refund. You can’t approve refunds. You note…", ["Refund approved.", "Customer requests refund for (order #); not within my authority; escalated to (team) ref #, customer informed of next steps.", "No.", "Nothing"], 1, "Say what was asked, who decides, the reference, and what the customer was told."],
  ["e-complaint", "How do you note a complaint about a driver?", ["Driver was rude.", "Customer states the driver left the item at the curb instead of the garage on 6/12; reported to (team) ref #.", "Nothing", "Driver is bad"], 1, "“Customer states…” plus the facts and the reference. Fair to everyone."],
  // ---- Sensitive data & wording
  ["x-ssn", "The customer reads you their social security number. In the note you write…", ["The full number", "Nothing about the number — never record it", "The last 4 digits always", "The number with dashes"], 1, "Never write personal ID numbers in notes. If your process needs verification, note only that it was verified."],
  ["x-verified", "You verified the customer’s identity. How do you note it?", ["Write all the data they gave", "“Identity verified per process”", "Nothing", "Their date of birth"], 1, "Note THAT you verified, not the private data you verified with."],
  ["x-medical", "The customer mentions a medical condition as the reason to reschedule. Note?", ["Write the diagnosis", "Customer requested a new date for personal reasons — no medical details", "Nothing at all", "Ask more about it"], 1, "Keep private details out. “Personal reasons” is enough."],
  ["x-emotional", "The customer was upset. Best wording?", ["Customer was crazy angry.", "Customer upset about the delay; asked for a supervisor.", "Rude customer.", "Customer yelled a lot."], 1, "Describe what they asked or said, not a judgment. Notes can be read by many people."],
  ["x-slang", "Which note sounds professional?", ["lol cx said its broke", "Customer reports the washer door is cracked.", "Broke stuff again", "cx mad, smh"], 1, "Plain, professional words. Read it as if the customer might see it."],
  ["x-blame", "A delay was caused by a warehouse issue. How do you note it?", ["Warehouse messed up again.", "Delivery delayed due to warehouse issue (per system update 6/11); new date 6/14.", "Not our fault.", "Blame the driver"], 1, "Facts and source, no blame. The note explains, it doesn’t accuse."],
  ["x-assume", "You’re not sure why the delivery failed. What do you write?", ["Your best guess as a fact", "What you know, its source, and that the cause is being confirmed", "Nothing", "Customer was not home (probably)"], 1, "Never write guesses as facts. Say what’s known and what’s pending."],
  ["x-abbrev-ok", "Which abbreviation is fine in a note?", ["“ETA”, “VM”, “ref #”", "“cx ntfd wl cb”", "Your own shortcuts", "Emojis"], 0, "Only standard abbreviations everyone knows."],
  ["x-caps", "Is writing in ALL CAPS good for a note?", ["Yes, it’s clearer", "No — it reads as shouting and is harder to scan", "Only for dates", "Only when upset"], 1, "Normal sentence case reads faster and stays professional."],
  // ---- QA lens
  ["q-complete", "QA marks a note “incomplete”. What was most likely missing?", ["Emojis", "One of: who, what happened, the action, or the next step", "The weather", "A greeting"], 1, "Run the four-part check before you save — it’s what QA checks first."],
  ["q-accurate", "QA marks a note “inaccurate”. What happened?", ["It was too short", "The note doesn’t match what happened in the call (dates, numbers, promises)", "It had no emojis", "It was written in English"], 1, "Accuracy means the note and the call tell the same story."],
  ["q-review", "A teammate reads your note and still has to call the customer to understand. The note…", ["Did its job", "Missed something important", "Was perfect", "Was too short to read"], 1, "If someone needs to call back to understand, the note didn’t finish its job."],
  ["q-self-check", "Your 5-second self-check before saving a note is…", ["Spell-check only", "Could a teammate act on this without asking me?", "Count the words", "Add more adjectives"], 1, "If a teammate could act on it alone, it’s a good note."],
  ["q-pattern", "QA flags the same thing in two of your audits. Best response?", ["Ignore it", "Make that one thing your focus for the next notes", "Write longer notes everywhere", "Stop writing notes"], 1, "One habit at a time. Fix the repeat and your audits improve fast."],
  ["q-why-audit", "Why does QA audit notes?", ["To punish agents", "To keep notes useful for customers and teammates, and to coach", "Because it’s random", "To count words"], 1, "Audits are coaching: they keep everyone’s notes useful."],
  ["q-best", "Which note would pass QA?", ["Called. Done.", "Outbound to Luis Gómez (account holder) re: 6/12 delivery; confirmed 8–12 window and address. No changes. Next: none.", "Talked about delivery stuff.", "Customer ok."], 1, "Short, complete and specific — even “no changes, next: none” is a complete outcome."],
  // ---- Why it matters
  ["w-weekend", "You’re off tomorrow and promised a callback. What makes sure it happens?", ["Remember it Monday", "A clear note with the callback date, time, number and reason", "Tell a friend", "Nothing"], 1, "The note is what keeps your promise when you’re not there."],
  ["w-customer-sees", "Why write every note as if the customer could read it?", ["They never will", "It keeps notes factual, respectful and professional", "To make them longer", "Because QA says so"], 1, "If you’d be comfortable with the customer reading it, it’s a good note."],
  ["w-team", "Who benefits most from a great note?", ["Only you", "The next agent and the customer", "Nobody", "Only QA"], 1, "Great notes are teamwork: the next agent starts ahead and the customer feels heard."],
  ["w-dispute", "Months later, a customer disputes what was agreed. What helps most?", ["Your memory", "A clear, dated note of what was agreed", "The customer’s memory", "A guess"], 1, "Dated, factual notes are the record everyone trusts."],
  ["w-speed", "How do good notes make you faster?", ["They don’t", "You and your team stop re-asking and re-checking the same things", "They make calls longer", "Only on Fridays"], 1, "A minute on the note saves many minutes later."],
];

export const EXTRA_QUESTIONS: QuizQuestion[] = RAW.map(([id, prompt, options, answer, tip]) => ({ id, prompt, options, answer, tip }));
