// GENERATED by tools/build-rocky-rig.py — do not edit by hand.
// Rig points per approved artwork, as fractions of the 512x512 canvas.
import type { EvolutionStage, Mood } from '../types/domain'

export interface RockyRigPoints {
  neck: number
  pivot: { x: number; y: number }
  chest: number
  feet: number
  top: number
}

export const ROCKY_RIG: Record<EvolutionStage, Record<Mood, RockyRigPoints>> = {
  "Advanced": {
    "Happy": {
      "neck": 0.4629,
      "pivot": {
        "x": 0.544,
        "y": 0.4512
      },
      "chest": 0.5958,
      "feet": 0.9375,
      "top": 0.0586
    },
    "Motivated": {
      "neck": 0.4707,
      "pivot": {
        "x": 0.544,
        "y": 0.459
      },
      "chest": 0.6014,
      "feet": 0.9375,
      "top": 0.0586
    },
    "Recovery": {
      "neck": 0.4551,
      "pivot": {
        "x": 0.5033,
        "y": 0.4434
      },
      "chest": 0.5721,
      "feet": 0.873,
      "top": 0.1211
    },
    "Worried": {
      "neck": 0.4688,
      "pivot": {
        "x": 0.5323,
        "y": 0.457
      },
      "chest": 0.6011,
      "feet": 0.9414,
      "top": 0.0625
    }
  },
  "Baby": {
    "Happy": {
      "neck": 0.5742,
      "pivot": {
        "x": 0.541,
        "y": 0.5625
      },
      "chest": 0.6759,
      "feet": 0.9375,
      "top": 0.0586
    },
    "Motivated": {
      "neck": 0.5098,
      "pivot": {
        "x": 0.5417,
        "y": 0.498
      },
      "chest": 0.6295,
      "feet": 0.9375,
      "top": 0.0586
    },
    "Recovery": {
      "neck": 0.5508,
      "pivot": {
        "x": 0.506,
        "y": 0.5391
      },
      "chest": 0.6591,
      "feet": 0.9375,
      "top": 0.0586
    },
    "Worried": {
      "neck": 0.5645,
      "pivot": {
        "x": 0.5352,
        "y": 0.5527
      },
      "chest": 0.6689,
      "feet": 0.9375,
      "top": 0.0586
    }
  },
  "Elite": {
    "Happy": {
      "neck": 0.4414,
      "pivot": {
        "x": 0.5584,
        "y": 0.4297
      },
      "chest": 0.5803,
      "feet": 0.9375,
      "top": 0.0586
    },
    "Motivated": {
      "neck": 0.4414,
      "pivot": {
        "x": 0.5599,
        "y": 0.4297
      },
      "chest": 0.5803,
      "feet": 0.9375,
      "top": 0.0586
    },
    "Recovery": {
      "neck": 0.4121,
      "pivot": {
        "x": 0.5128,
        "y": 0.4004
      },
      "chest": 0.5516,
      "feet": 0.9102,
      "top": 0.0605
    },
    "Worried": {
      "neck": 0.4336,
      "pivot": {
        "x": 0.5307,
        "y": 0.4219
      },
      "chest": 0.5747,
      "feet": 0.9375,
      "top": 0.0586
    }
  },
  "Young": {
    "Happy": {
      "neck": 0.5332,
      "pivot": {
        "x": 0.5469,
        "y": 0.5215
      },
      "chest": 0.6245,
      "feet": 0.8594,
      "top": 0.2109
    },
    "Motivated": {
      "neck": 0.4883,
      "pivot": {
        "x": 0.5186,
        "y": 0.4766
      },
      "chest": 0.6152,
      "feet": 0.9414,
      "top": 0.0605
    },
    "Recovery": {
      "neck": 0.5586,
      "pivot": {
        "x": 0.4834,
        "y": 0.5469
      },
      "chest": 0.6455,
      "feet": 0.8691,
      "top": 0.2441
    },
    "Worried": {
      "neck": 0.5488,
      "pivot": {
        "x": 0.5049,
        "y": 0.5371
      },
      "chest": 0.6571,
      "feet": 0.9355,
      "top": 0.0605
    }
  }
}
