// GENERATED by tools/build-rocky-anchors.py — do not edit by hand.
// Head anchor per approved artwork, as fractions of the 512x512 canvas:
// x/y = top-centre of the head (hair tuft), w = face width, figureTop/Bottom = art extent.
import type { EvolutionStage, Mood } from '../types/domain'

export interface HeadAnchor {
  x: number
  y: number
  w: number
  figureTop: number
  figureBottom: number
}

export const ROCKY_HEAD_ANCHORS: Record<EvolutionStage, Record<Mood, HeadAnchor>> = {
  "Advanced": {
    "Happy": {
      "x": 0.508,
      "y": 0.0586,
      "w": 0.4238,
      "figureTop": 0.0586,
      "figureBottom": 0.9375
    },
    "Motivated": {
      "x": 0.5103,
      "y": 0.0586,
      "w": 0.4082,
      "figureTop": 0.0586,
      "figureBottom": 0.9375
    },
    "Recovery": {
      "x": 0.4988,
      "y": 0.1211,
      "w": 0.3438,
      "figureTop": 0.1211,
      "figureBottom": 0.873
    },
    "Worried": {
      "x": 0.4988,
      "y": 0.0625,
      "w": 0.4102,
      "figureTop": 0.0625,
      "figureBottom": 0.9414
    }
  },
  "Baby": {
    "Happy": {
      "x": 0.511,
      "y": 0.0586,
      "w": 0.5078,
      "figureTop": 0.0586,
      "figureBottom": 0.9375
    },
    "Motivated": {
      "x": 0.5043,
      "y": 0.0586,
      "w": 0.4902,
      "figureTop": 0.0586,
      "figureBottom": 0.9375
    },
    "Recovery": {
      "x": 0.501,
      "y": 0.0586,
      "w": 0.4883,
      "figureTop": 0.0586,
      "figureBottom": 0.9375
    },
    "Worried": {
      "x": 0.504,
      "y": 0.0586,
      "w": 0.5156,
      "figureTop": 0.0586,
      "figureBottom": 0.9375
    }
  },
  "Elite": {
    "Happy": {
      "x": 0.5213,
      "y": 0.0586,
      "w": 0.3887,
      "figureTop": 0.0586,
      "figureBottom": 0.9375
    },
    "Motivated": {
      "x": 0.5262,
      "y": 0.0586,
      "w": 0.3828,
      "figureTop": 0.0586,
      "figureBottom": 0.9375
    },
    "Recovery": {
      "x": 0.5071,
      "y": 0.0605,
      "w": 0.3691,
      "figureTop": 0.0605,
      "figureBottom": 0.9102
    },
    "Worried": {
      "x": 0.5059,
      "y": 0.0586,
      "w": 0.3809,
      "figureTop": 0.0586,
      "figureBottom": 0.9375
    }
  },
  "Young": {
    "Happy": {
      "x": 0.5268,
      "y": 0.2109,
      "w": 0.3086,
      "figureTop": 0.2109,
      "figureBottom": 0.8594
    },
    "Motivated": {
      "x": 0.4806,
      "y": 0.0605,
      "w": 0.4258,
      "figureTop": 0.0605,
      "figureBottom": 0.9414
    },
    "Recovery": {
      "x": 0.4817,
      "y": 0.2441,
      "w": 0.3418,
      "figureTop": 0.2441,
      "figureBottom": 0.8691
    },
    "Worried": {
      "x": 0.4733,
      "y": 0.0605,
      "w": 0.4609,
      "figureTop": 0.0605,
      "figureBottom": 0.9355
    }
  }
}
