"""Measure the 2.5D "rig" points of each approved Rocky artwork.

Writes src/components/rockyRig.ts: for every stage/mood PNG, the points the
mesh-deformation renderer (src/components/world/RockyRig.tsx) needs, as
fractions of the 512x512 canvas:

  neck   — the chin/vest line; above it the head moves, below it the body.
  pivot  — where the head rotates: centred between the eyes, just above
           the neck line.
  chest  — centre of the breathing area.
  feet   — bottom of the figure (body squash/stretch anchor).

The eyes are only used to centre the head pivot. They're found from the
white catch-light inside each pupil (the most reliable mark of an open eye
in this art style), with hand-checked overrides where the automatic pass
was fooled. The face itself is never painted over (no fake eyelids).

    python3 tools/build-rocky-rig.py
"""
import glob
import json
import os

from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Eye catch-lights (px, 512 canvas) — confirmed by eye on every artwork.
# The eye centre is the centroid of the dark pupil around each catch-light.
HIGHLIGHTS = {
    ('advanced', 'happy'): [(234, 143), (321, 145)],
    ('advanced', 'motivated'): [(233, 145), (322, 153)],
    ('advanced', 'recovery'): [(232, 157), (303, 154)],
    ('advanced', 'worried'): [(225, 150), (316, 156)],
    ('baby', 'motivated'): [(225, 162), (329, 164)],
    ('baby', 'worried'): [(221, 180), (329, 176)],
    ('elite', 'happy'): [(244, 135), (321, 138)],
    ('elite', 'motivated'): [(246, 137), (323, 135)],
    ('elite', 'recovery'): [(235, 140), (313, 140)],
    ('elite', 'worried'): [(231, 142), (309, 152)],
    ('young', 'motivated'): [(216, 151), (309, 157)],
    ('young', 'worried'): [(205, 169), (311, 173)],
}
# Eye centres measured directly where catch-lights were ambiguous.
CENTRES = {
    ('baby', 'happy'): [(230, 186), (324, 182)],
    ('young', 'happy'): [(254, 217), (306, 217)],
    ('young', 'motivated'): [(226, 163), (305, 162)],
    ('young', 'worried'): [(219, 179), (298, 179)],
}
# Eyes already closed in the art: the pivot uses the head's centre line.
CLOSED_EYES = {('baby', 'recovery'), ('young', 'recovery'), ('advanced', 'recovery'), ('elite', 'recovery')}


def lum(p):
    return 0.3 * p[0] + 0.59 * p[1] + 0.11 * p[2]


def pupil_centre(px, hx, hy, radius=22):
    pts = [
        (x, y)
        for y in range(hy - radius, hy + radius + 1)
        for x in range(hx - radius, hx + radius + 1)
        if (x - hx) ** 2 + (y - hy) ** 2 <= radius * radius and px[x, y][3] > 200 and lum(px[x, y]) < 60
    ]
    if len(pts) < 20:
        return (hx - 5, hy + 9)
    return (sum(p[0] for p in pts) / len(pts), sum(p[1] for p in pts) / len(pts))


def measure(path, stage, mood):
    im = Image.open(path).convert('RGBA')
    w, h = im.size
    px = im.load()
    rows = [y for y in range(h) if any(px[x, y][3] > 128 for x in range(0, w, 2))]
    top, bottom = rows[0], rows[-1]
    head_xs = [x for y in range(top, top + 80) for x in range(0, w, 2) if px[x, y][3] > 128]
    cx = sum(head_xs) / len(head_xs)
    # Neck = first row where the green vest shows around the centre line.
    neck = next(
        y
        for y in range(top + 60, h)
        if sum(1 for x in range(int(cx - 40), int(cx + 40), 2) if px[x, y][3] > 200 and px[x, y][1] > px[x, y][0] + 15 and px[x, y][1] > px[x, y][2]) > 8
    )

    key = (stage, mood)
    if key in CLOSED_EYES:
        centres = []
    elif key in CENTRES:
        centres = CENTRES[key]
    else:
        centres = [pupil_centre(px, hx, hy) for hx, hy in HIGHLIGHTS[key]]
    pivot_x = (centres[0][0] + centres[1][0]) / 2 if centres else cx

    return {
        'neck': round(neck / h, 4),
        'pivot': {'x': round(pivot_x / w, 4), 'y': round((neck - 6) / h, 4)},
        'chest': round((neck + (bottom - neck) * 0.28) / h, 4),
        'feet': round(bottom / h, 4),
        'top': round(top / h, 4),
    }


def main():
    rig = {}
    for path in sorted(glob.glob(os.path.join(ROOT, 'src/assets/rocky/*/*.png'))):
        stage = os.path.basename(os.path.dirname(path))
        if stage == 'reactions':
            continue
        mood = os.path.splitext(os.path.basename(path))[0]
        rig.setdefault(stage.capitalize(), {})[mood.capitalize()] = measure(path, stage, mood)
    out = os.path.join(ROOT, 'src/components/rockyRig.ts')
    with open(out, 'w') as f:
        f.write('// GENERATED by tools/build-rocky-rig.py — do not edit by hand.\n')
        f.write('// Rig points per approved artwork, as fractions of the 512x512 canvas.\n')
        f.write("import type { EvolutionStage, Mood } from '../types/domain'\n\n")
        f.write('export interface RockyRigPoints {\n  neck: number\n  pivot: { x: number; y: number }\n  chest: number\n  feet: number\n  top: number\n}\n\n')
        f.write('export const ROCKY_RIG: Record<EvolutionStage, Record<Mood, RockyRigPoints>> = ')
        f.write(json.dumps(rig, indent=2))
        f.write('\n')
    print('wrote', out)


if __name__ == '__main__':
    main()
