"""Measure where Rocky's head sits in each approved artwork.

Writes src/components/rockyAnchors.ts: for every stage/mood PNG, the head's
top-centre point and width as fractions of the 512x512 canvas. Wardrobe
items (hats, headsets...) are positioned from these anchors, so they sit on
Rocky's head without ever redrawing or editing the approved art.

Run from the repo root after the artwork changes:
    python3 tools/build-rocky-anchors.py
"""
import glob
import json
import os

from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
anchors = {}
for path in sorted(glob.glob(os.path.join(ROOT, 'src/assets/rocky/*/*.png'))):
    stage = os.path.basename(os.path.dirname(path))
    if stage == 'reactions':
        continue
    mood = os.path.splitext(os.path.basename(path))[0]
    im = Image.open(path).convert('RGBA')
    alpha = im.split()[3].load()
    w, h = im.size
    rows = [y for y in range(h) if any(alpha[x, y] > 128 for x in range(0, w, 2))]
    top, bottom = rows[0], rows[-1]
    fig_h = bottom - top
    band = [x for y in range(top, int(top + fig_h * 0.30)) for x in range(0, w, 2) if alpha[x, y] > 128]
    cx = sum(band) / len(band)
    # Top of the hair tuft: the highest opaque pixel close to the head centre
    # (the horns stick up further out to the sides and are excluded).
    cols = range(int(cx - w * 0.06), int(cx + w * 0.06))
    hair_top = min(y for y in range(h) for x in cols if alpha[x, y] > 128)
    # Head width, measured across the face below the horns.
    y_face = int(top + fig_h * 0.24)
    xs = [x for x in range(w) if alpha[x, y_face] > 128]
    anchors.setdefault(stage.capitalize(), {})[mood.capitalize()] = {
        'x': round(cx / w, 4),
        'y': round(hair_top / h, 4),
        'w': round((xs[-1] - xs[0]) / w, 4),
        'figureTop': round(top / h, 4),
        'figureBottom': round(bottom / h, 4),
    }

out = os.path.join(ROOT, 'src/components/rockyAnchors.ts')
with open(out, 'w') as f:
    f.write('// GENERATED by tools/build-rocky-anchors.py — do not edit by hand.\n')
    f.write("// Head anchor per approved artwork, as fractions of the 512x512 canvas:\n")
    f.write('// x/y = top-centre of the head (hair tuft), w = face width, figureTop/Bottom = art extent.\n')
    f.write("import type { EvolutionStage, Mood } from '../types/domain'\n\n")
    f.write('export interface HeadAnchor {\n  x: number\n  y: number\n  w: number\n  figureTop: number\n  figureBottom: number\n}\n\n')
    f.write('export const ROCKY_HEAD_ANCHORS: Record<EvolutionStage, Record<Mood, HeadAnchor>> = ')
    f.write(json.dumps(anchors, indent=2))
    f.write('\n')
print('wrote', out)
